name: Debug Build

on: [push]

jobs:
  debug-build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Show structure
      run: |
        Get-ChildItem -Recurse | Select-Object FullName
    
    - name: Configure
      run: cmake -B build -A Win32
    
    - name: Build
      run: cmake --build build --config Release --verbose
    
    - name: Find exe
      run: |
        Get-ChildItem -Recurse -Filter *.exe | Select-Object FullName
